### ISSUE TITLE
Class Cast Exception with Decision Node and Case value

### ISSUE THREAD

**Issue by larsgeorge** [mashin-io/oep#1]
I tried to edit a "line" to set the condition for a decision node, by clicking the one that is connected to the "case" endpoint of the icon, and the subsequent action. The properties were not editable. I then edited the XML directly, inserting the condition (a simple check for `true`, for example, `${var}`) I needed. But now when trying to save the same workflow from the Oozie editor I get the following error:

```
An error has occurred. See error log for more details.
io.mashin.oep.model.connection.WorkflowConnection cannot be cast to io.mashin.oep.model.connection.WorkflowCaseConnection
```

**Comment by ahmed-mahran** [comment]
Thanks for the report :+1: 

Issue is now fixed on version 0.3.3 http://oep.mashin.io/version-history/version033
