### ISSUE TITLE
Please share the code of this plugin.

### ISSUE THREAD

**Issue by kamir** [mashin-io/oep#2]
The screenshot looks (https://qph.is.quoracdn.net/main-qimg-a9f9587674fa068609ff6a48b43d38d2?convert_to_webp=true) great, but how can I contribute if no code is public?

Please tell us, if it is an open source project, and which license applies.

**Comment by ahmed-mahran** [comment]
@kamir, currently, it is a closed source however free software but it will be opened very soon (maybe under Apache 2 license)
What license would you suggest?

**Comment by kamir** [comment]
We usually use Apache 2 a lot. Since it is Hadoop related it seems to be a good idea to be in line with the general Hadoop license. But I am not an expert in licenses. All kinds of open source which allows building a community around a great software sounds like a huge win.
Best wishes,
Mirko

**Comment by ahmed-mahran** [comment]
@kamir it's open now
looking forward for your participation
