### ISSUE TITLE
Propagate configuration

### ISSUE THREAD

**Issue by PetrBechynak** [mashin-io/oep#3]
Hi, first of all - thx for this Eclipse plugin!

Opening and saving a workflow causes propagate flag (tag <propagate-configuration/>) to be set to false, which is very annoying. The sub-workflows fail as a result...

**Comment by ahmed-mahran** [comment]
Thanks @PetrBechynak for reporting the issue :+1: 
This issue should be fixed now, you may update your installed version to the latest (v0.3.4)
